spring:
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED}
      settings.web-allow-others: ${H2_WEB_ALLOW_OTHERS}
  datasource:
    url: ${H2_URL}
    username: ${H2_USERNAME}
    password: ${H2_PASSWORD}
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
server:
  error:
    include-stacktrace: never
